### ISSUE TITLE
Failed to bind to address.

### ISSUE THREAD

**Issue by RapidtSoftware** [GlowstoneMC/Glowstone-Legacy#548]
When I start up my server it says:

```
17:02:36 [SEVERE] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in use?
    at net.glowstone.GlowServer.bind(GlowServer.java:431)
    at net.glowstone.GlowServer.main(GlowServer.java:92)
```

Glowstone.yml:

```
# glowstone.yml is the main configuration file for a Glowstone server
# It contains everything from server.properties and bukkit.yml in a
# normal CraftBukkit installation.
#
# For help, join us on IRC: #glowstone @ esper.net

server: 
    ip: minekart.tk
    port: 
    name: MineKart
    online-mode: false
    max-players: 20
    whitelisted: false
    motd: Welcome to the MineKart server!
    shutdown-message: Server shutting down, sorry for the inconvinience!

folders:
    plugins: plugins
    update: update
    worlds: worlds

world:
    name: world
    spawn-radius: 16
    view-distance: 8
    gen-structures: true
    allow-nether: true
    allow-end: true
```

Please help me?
