### ISSUE TITLE
Starting server doesn't work

### ISSUE THREAD

**Issue by Verald** [GlowstoneMC/Glowstone-Legacy#589]
Whatever i give it to port (even 25565) or the server (even localhost) it just doesn't work

failed to bind to address

**Comment by gdude2002** [comment]
Can you paste your full server logs, please?

For reference, config..

``` yaml
# glowstone.yml is the main configuration file for a Glowstone server
# It contains everything from server.properties and bukkit.yml in a
# normal CraftBukkit installation.
#
# For help, join us on IRC: #glowstone @ esper.net

server:
    port: 25565
    name: Glowstone Server
    online-mode: true
    max-players: 20
    whitelisted: false
    motd: Glowstone Server
    shutdown-message: Server shutting down

folders:
    plugins: plugins
    update: update
    worlds: worlds

world:
    name: world
    spawn-radius: 16
    view-distance: 8
    gen-structures: true
    allow-nether: true
    allow-end: true
```
