### ISSUE TITLE
Add ability to specify World Generator (and settings) for every stock world

### ISSUE THREAD

**Issue by Ribesg** [GlowstoneMC/Glowstone-Legacy#630]
The `world` section of `glowstone.yml` would then look like this, for example:

``` yml
world:
    name: world
    # [...]
    generator: MyGeneratorPlugin:Overworld
    allow-nether: true
    nether-generator: MyGeneratorPlugin:Nether
    allow-end: true
    end-generator: MyGeneratorPlugin:End

```

**Comment by Ribesg** [comment]
I found that, as the behaviour of things seems to have been copy-pasted from Bukkit basically, you can define generators the same way you do in Bukkit:

``` yml
world:
    name: world
    # [...]

worlds:
    world:
        generator: MyGeneratorPlugin:Overworld
    world_nether:
        generator: MyGeneratorPlugin:Nether
    world_the_end:
        generator: MyGeneratorPlugin:End
```

It works, but maybe it's a bit weird.
